### ISSUE TITLE
generic: add extraObjects

### ISSUE THREAD

**Issue by CygnusHyoga** [morremeyer/charts#320]
Hello! I've a recommendation for generic helm chart, define an extraObjects: [] for create extra manifests via values. (for ex. extra pv, extra pvc, extra cm, or any other k8s object)

Thanks! I use generic helm chart a lot :-)

**Comment by morremeyer** [comment]
@CygnusHyoga That's a great idea, thanks. I'll implement it when I get to it.

**Comment by ekeih** [comment]
@CygnusHyoga `7.1.0` will be released in a few minutes. Please give it a try and open an issue if it does not work as expected.

**Comment by CygnusHyoga** [comment]
It's working perfect! Thanks!!
