### ISSUE TITLE
generic: Add startupProbe

### ISSUE THREAD

**Issue by ibexa-yuna** [morremeyer/charts#98]
The generic chart should have startupProbe for pods so that it's possible to setup startupProbe, similar to livenessProbe

**Comment by morremeyer** [comment]
I agree :) I will look into it next week.

**Comment by ekeih** [comment]
@ibexa-yuna support for startup probes has been added in [3.3.0](https://github.com/morremeyer/charts/releases/tag/generic-3.3.0).
